import { writeFileSync } from 'fs';
import { join } from 'path';
import type { FafData, ScoreResult } from '../core/types.js';

/**
 * project.html — the visual render of project.faf.
 *
 * A "show-me" for .faf: rendered from the current project.faf, opens in any
 * browser, zero deps, self-contained. NOT a format, NOT a mime-type, NOT an
 * IANA application — a derived view that registers nothing and adds zero spec
 * surface. The inverse of style-source.html (that one is authored; this is
 * rendered). Deterministic on purpose: no timestamps, so a regenerate only
 * diffs when project.faf actually changed (versioned like .fafb).
 *
 * Humans like visuals. We gave them one.
 */

/** Canonical tier glyph + accent — evergreen constants (see core/tiers.ts). */
const TIER_VIS: Record<string, { glyph: string; color: string }> = {
  TROPHY: { glyph: '🏆', color: '#FF6B35' },
  GOLD: { glyph: '★', color: '#FFB000' },
  SILVER: { glyph: '◆', color: '#00D4D4' },
  BRONZE: { glyph: '◇', color: '#00D4D4' },
  GREEN: { glyph: '●', color: '#3FB950' },
  YELLOW: { glyph: '●', color: '#D4A017' },
  RED: { glyph: '○', color: '#8B949E' },
  WHITE: { glyph: '♡', color: '#6E7681' },
};

/** HTML-escape — project.faf content is arbitrary; never inject raw. */
function esc(v: unknown): string {
  return String(v ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

const SIX_W = ['who', 'what', 'why', 'where', 'when', 'how'] as const;

function rows(entries: [string, unknown][]): string {
  return entries
    .filter(([, v]) => v !== undefined && v !== null && String(v).trim() !== '')
    .map(
      ([k, v]) =>
        `<div class="row"><div class="k">${esc(k)}</div><div class="v">${esc(v)}</div></div>`,
    )
    .join('\n');
}

/** Render project.faf data + its score into a self-contained HTML string. */
export function generateProjectHtml(
  data: FafData,
  result: ScoreResult,
  fafPath = 'project.faf',
): string {
  const name = esc(data.project?.name ?? 'Project');
  const tierName = result.tier?.name ?? 'WHITE';
  const vis = TIER_VIS[tierName] ?? TIER_VIS.WHITE;
  const scoreText = result.inherited
    ? result.represents
      ? `inherited from ${esc(result.represents)}`
      : 'inherited'
    : `${result.score}%`;

  // 6 W's first, in canonical order, then any other human_context keys.
  const hc = data.human_context ?? {};
  const sixW: [string, unknown][] = SIX_W.map((w) => [w, hc[w]]);
  const otherHc = Object.entries(hc).filter(
    ([k]) => !SIX_W.includes(k as (typeof SIX_W)[number]),
  );

  const projectMeta: [string, unknown][] = [
    ['goal', data.project?.goal],
    ['main_language', data.project?.main_language],
    ['type', data.project?.type],
    ['framework', (data.project as Record<string, unknown> | undefined)?.framework],
    ['faf_version', data.faf_version],
  ];

  const stackEntries = Object.entries(data.stack ?? {});
  const stackActive = stackEntries.filter(
    ([, v]) => v && v !== 'slotignored' && String(v).trim() !== '',
  );
  const stackIgnored = stackEntries.filter(([, v]) => v === 'slotignored').length;

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${name} — project.faf</title>
<meta name="description" content="Visual render of project.faf. Generated by faf — humans like visuals, we gave them one.">
<meta name="robots" content="index,follow">
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;background:#0a0a0a;color:#e6edf3;line-height:1.55;padding:48px 20px}
.wrap{max-width:880px;margin:0 auto}
.bar{height:3px;border-radius:2px;background:linear-gradient(90deg,transparent,${vis.color},transparent);margin-bottom:40px}
header{display:flex;align-items:baseline;gap:16px;flex-wrap:wrap;margin-bottom:8px}
h1{font-size:2.2rem;font-weight:800;letter-spacing:-1px}
.badge{font-size:1.05rem;font-weight:800;color:${vis.color};white-space:nowrap}
.score{font-size:1.05rem;font-weight:700;color:#8b949e}
.eyebrow{font-size:11px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:#6e7681;margin-bottom:36px}
section{margin-bottom:34px}
h2{font-size:12px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:${vis.color};margin-bottom:14px;padding-bottom:6px;border-bottom:1px solid rgba(255,255,255,.07)}
.row{display:flex;gap:18px;padding:8px 0;border-bottom:1px solid rgba(255,255,255,.04)}
.k{flex:0 0 150px;color:#8b949e;font-size:.9rem;text-transform:capitalize}
.v{flex:1;color:#e6edf3;font-size:.95rem;word-break:break-word}
.meter{height:8px;border-radius:4px;background:rgba(255,255,255,.06);overflow:hidden;margin:6px 0 10px}
.meter span{display:block;height:100%;background:${vis.color};width:${Math.max(0, Math.min(100, result.score))}%}
.muted{color:#6e7681;font-size:.85rem}
footer{margin-top:48px;padding-top:20px;border-top:1px solid rgba(255,255,255,.07);font-size:.82rem;color:#6e7681}
footer strong{color:#e6edf3}
@media(max-width:560px){.row{flex-direction:column;gap:2px}.k{flex:none}}
</style>
</head>
<body>
<div class="wrap">
<div class="bar"></div>
<div class="eyebrow">project.faf · visual render</div>
<header>
<h1>${name}</h1>
<span class="badge">${vis.glyph} ${esc(tierName)}</span>
<span class="score">${scoreText}</span>
</header>
<div class="meter"><span></span></div>
<p class="muted">${result.populated}/${result.active} slots populated · ${result.total} total${stackIgnored ? ` · ${stackIgnored} slotignored` : ''}</p>

<section>
<h2>The 6 W's</h2>
${rows(sixW) || '<p class="muted">No human_context yet.</p>'}
${otherHc.length ? rows(otherHc) : ''}
</section>

<section>
<h2>Project</h2>
${rows(projectMeta) || '<p class="muted">—</p>'}
</section>

<section>
<h2>Stack</h2>
${
  stackActive.length
    ? rows(stackActive)
    : '<p class="muted">No active stack slots.</p>'
}
</section>

<footer>
Rendered on-demand from your current <strong>${esc(fafPath)}</strong><br>
<strong>Humans like visuals. We gave them one.</strong>
</footer>
</div>
</body>
</html>
`;
}

/** Write project.html beside project.faf (repo root). */
export function writeProjectHtml(
  dir: string,
  data: FafData,
  result: ScoreResult,
  fafPath = 'project.faf',
): void {
  writeFileSync(
    join(dir, 'project.html'),
    generateProjectHtml(data, result, fafPath),
    'utf-8',
  );
}
