/**
 * WJTTC — FAFB v1.0 round-trip parity (faf-cli ↔ xai-faf-rust)
 *
 * BRAKE TIER. This is THE conformance gate.
 *
 * Same .faf input compiled by faf-cli (via faf-scoring-kernel WASM) MUST
 * produce byte-identical .fafb output to the xai-faf-rust reference
 * implementation (which uses faf-rust-sdk's binary module — the canonical
 * spec).
 *
 * If this test fails, the cli has drifted from FAFB v1.0 spec conformance.
 * Either:
 *   (a) the WASM kernel was rebuilt with a different schema/algorithm — fix.
 *   (b) the reference fixture was regenerated from a different ref impl —
 *       update both fixture AND xai-faf-rust to match.
 *   (c) xai-faf-rust changed its compile output (e.g. someone reverted the
 *       deterministic-timestamp fix and is writing real Unix time again) —
 *       restore the determinism fix in xai-faf-rust/src/commands/compile.rs.
 *
 * The fixture (parity-expected.fafb) was generated by:
 *   xai-faf compile -i tests/fixtures/parity/parity-input.faf \
 *                   -o tests/fixtures/parity/parity-expected.fafb
 *
 * with xai-faf-rust @ commit d5236ad (timestamp determinism applied).
 *
 * Doctrine:
 * - faf-dont-lie-deterministic-scoring — same input, same output, byte-true
 * - feedback-semver-receipts-not-promises — this test IS the receipt that
 *   justifies the "FAFB v1.0 conformant" claim in v6.5.0+ CHANGELOGs
 * - quiet-receipt-doctrine — the byte-cmp is the receipt; no marketing prose
 */

import { describe, test, expect } from 'bun:test';
import { readFileSync } from 'fs';
import { join } from 'path';
import * as kernel from '../src/wasm/kernel.js';

const FIXTURES = join(__dirname, 'fixtures/parity');

describe('WJTTC BRAKE: FAFB v1.0 round-trip parity gate (cli ↔ xai-faf-rust)', () => {
  test('cli compile is byte-identical to xai-faf-rust reference (META-only fixture)', () => {
    const inputYaml = readFileSync(join(FIXTURES, 'parity-input.faf'), 'utf-8');
    const expectedBytes = readFileSync(join(FIXTURES, 'parity-expected.fafb'));

    const actualBytes = Buffer.from(kernel.compile(inputYaml));

    if (!actualBytes.equals(expectedBytes)) {
      // Detailed byte-diff for fast triage on regression.
      const diffs: string[] = [];
      const maxLen = Math.max(actualBytes.length, expectedBytes.length);
      for (let i = 0; i < maxLen; i++) {
        const a = actualBytes[i];
        const e = expectedBytes[i];
        if (a !== e) {
          diffs.push(`offset ${i}: cli=${a !== undefined ? `0x${a.toString(16).padStart(2, '0')}` : 'EOF'} ref=${e !== undefined ? `0x${e.toString(16).padStart(2, '0')}` : 'EOF'}`);
        }
      }
      throw new Error(
        `FAFB byte-parity violated. cli=${actualBytes.length}b ref=${expectedBytes.length}b.\n` +
        `First ${Math.min(diffs.length, 16)} byte diff(s):\n  ${diffs.slice(0, 16).join('\n  ')}\n` +
        `\nIf the cli output looks correct, regenerate the fixture:\n` +
        `  xai-faf compile -i tests/fixtures/parity/parity-input.faf -o tests/fixtures/parity/parity-expected.fafb\n`,
      );
    }

    expect(actualBytes.equals(expectedBytes)).toBe(true);
  });

  test('fixture has the canonical FAFB v1.0 header layout', () => {
    const bytes = readFileSync(join(FIXTURES, 'parity-expected.fafb'));
    // Magic
    expect(bytes.subarray(0, 4).toString('ascii')).toBe('FAFB');
    // Version 1.0
    expect(bytes[4]).toBe(1);
    expect(bytes[5]).toBe(0);
    // Timestamp (offset 12-19) MUST be all zeros — determinism guarantee
    for (let i = 12; i < 20; i++) {
      expect(bytes[i]).toBe(0);
    }
  });

  test('cli compile produces a non-zero CRC32 over the YAML source', () => {
    const inputYaml = readFileSync(join(FIXTURES, 'parity-input.faf'), 'utf-8');
    const bytes = Buffer.from(kernel.compile(inputYaml));
    // CRC32 lives at offset 8-11 (little-endian u32)
    const crc = bytes.readUInt32LE(8);
    expect(crc).toBeGreaterThan(0);
  });

  test('cli compile is itself deterministic — same input, same output across calls', () => {
    const inputYaml = readFileSync(join(FIXTURES, 'parity-input.faf'), 'utf-8');
    const bytes1 = Buffer.from(kernel.compile(inputYaml));
    const bytes2 = Buffer.from(kernel.compile(inputYaml));
    const bytes3 = Buffer.from(kernel.compile(inputYaml));
    expect(bytes1.equals(bytes2)).toBe(true);
    expect(bytes2.equals(bytes3)).toBe(true);
  });
});
