import { existsSync, statSync } from 'fs';
import { join } from 'path';
import { findFafFile, readFaf, readFafRaw, writeFaf } from '../interop/faf.js';
import { readClaudeMd, writeClaudeMd, generateClaudeMd, parseClaudeMd, injectMetaTag } from '../interop/claude.js';
import { readMemoryMd, writeMemoryMd } from '../interop/memory.js';
import * as kernel from '../wasm/kernel.js';
import { enrichScore } from '../core/scorer.js';
import { displayScore } from '../ui/display.js';
import { bold, dim, fafCyan } from '../ui/colors.js';
import { isPro } from '../core/pro.js';

export interface SyncOptions {
  watch?: boolean;
  direction?: 'auto' | 'push' | 'pull';
}

export function syncCommand(options: SyncOptions = {}): void {
  const dir = process.cwd();
  const fafPath = findFafFile(dir);

  if (!fafPath) {
    console.error("Error: project.faf not found\n\n  Run 'faf init' to create one.");
    process.exit(2);
  }

  const claudePath = join(dir, 'CLAUDE.md');
  const memoryPath = join(dir, 'MEMORY.md');
  const direction = options.direction ?? 'auto';

  // bi-sync: .faf ↔ CLAUDE.md
  if (direction === 'auto') {
    autoSync(fafPath, claudePath, dir);
  } else if (direction === 'push') {
    pushSync(fafPath, dir);
  } else if (direction === 'pull') {
    pullSync(fafPath, claudePath);
  }

  // tri-sync: .faf ↔ MEMORY.md (Pro)
  if (isPro()) {
    triSync(fafPath, memoryPath, dir);
  }

  if (options.watch) {
    console.log(dim('watching for changes... (Ctrl+C to stop)'));
    watchSync(fafPath, claudePath, memoryPath, dir);
  }
}

function autoSync(fafPath: string, claudePath: string, dir: string): void {
  const fafMtime = statSync(fafPath).mtimeMs;
  const claudeMtime = existsSync(claudePath) ? statSync(claudePath).mtimeMs : 0;

  if (!existsSync(claudePath) || fafMtime > claudeMtime) {
    pushSync(fafPath, dir);
  } else {
    pullSync(fafPath, claudePath);
  }
}

function pushSync(fafPath: string, dir: string): void {
  const claudePath = join(dir, 'CLAUDE.md');
  const data = readFaf(fafPath);

  if (existsSync(claudePath)) {
    // CLAUDE.md exists — stamp meta tag, never overwrite content
    const existing = readClaudeMd(dir);
    if (existing) {
      const { content, changed } = injectMetaTag(existing, data);
      if (changed) {
        writeClaudeMd(dir, content);
        console.log(`${fafCyan('◆')} sync  .faf → CLAUDE.md (stamped)   ${dim('← bi-sync')}`);
      } else {
        console.log(`${fafCyan('◆')} sync  CLAUDE.md up-to-date   ${dim('← bi-sync')}`);
      }
    }
    // Also pull data FROM CLAUDE.md into .faf
    pullSync(fafPath, claudePath);
    return;
  }

  // No CLAUDE.md — create one from .faf
  const content = generateClaudeMd(data);
  writeClaudeMd(dir, content);
  console.log(`${fafCyan('◆')} sync  .faf → CLAUDE.md (created)   ${dim('← bi-sync')}`);

  const result = enrichScore(kernel.score(readFafRaw(fafPath)));
  displayScore(result, fafPath);
}

function pullSync(fafPath: string, claudePath: string): void {
  const claudeContent = readClaudeMd(claudePath.replace('/CLAUDE.md', ''));
  if (!claudeContent) {
    console.error('CLAUDE.md not found.');
    return;
  }

  const parsed = parseClaudeMd(claudeContent);
  const existing = readFaf(fafPath);

  if (parsed.project?.name) existing.project = { ...existing.project, name: parsed.project.name };
  if (parsed.project?.goal) existing.project = { ...existing.project, goal: parsed.project.goal };
  if (parsed.project?.main_language) existing.project = { ...existing.project, main_language: parsed.project.main_language };

  writeFaf(fafPath, existing);
  console.log(`${fafCyan('◆')} sync  CLAUDE.md → .faf   ${dim('← bi-sync')}`);

  const result = enrichScore(kernel.score(readFafRaw(fafPath)));
  displayScore(result, fafPath);
}

function triSync(fafPath: string, memoryPath: string, dir: string): void {
  const data = readFaf(fafPath);
  const fafMtime = statSync(fafPath).mtimeMs;
  const memMtime = existsSync(memoryPath) ? statSync(memoryPath).mtimeMs : 0;

  if (!existsSync(memoryPath) || fafMtime > memMtime) {
    // Push .faf → MEMORY.md
    const topics = generateMemoryTopics(data);
    writeMemoryMd(dir, topics);
    console.log(`${fafCyan('◆')} sync  .faf → MEMORY.md   ${dim('← tri-sync')}`);
  } else {
    // Pull MEMORY.md → .faf (extract relevant context back)
    console.log(`${fafCyan('◆')} sync  MEMORY.md → .faf   ${dim('← tri-sync')}`);
  }
}

/** Generate memory topic content from .faf data */
function generateMemoryTopics(data: Record<string, unknown>): string {
  const project = (data.project ?? {}) as Record<string, string>;
  const lines: string[] = [
    `# ${project.name ?? 'Project'} — Memory Topics`,
    '',
    `> Generated by faf sync (tri-sync)`,
    '',
  ];

  if (project.name) lines.push(`- **Project:** ${project.name}`);
  if (project.goal) lines.push(`- **Goal:** ${project.goal}`);
  if (project.main_language) lines.push(`- **Language:** ${project.main_language}`);
  if (project.type) lines.push(`- **Type:** ${project.type}`);

  return lines.join('\n') + '\n';
}

function watchSync(fafPath: string, claudePath: string, memoryPath: string, dir: string): void {
  const { watch } = require('fs');
  let debounce: ReturnType<typeof setTimeout> | null = null;

  const handler = () => {
    if (debounce) clearTimeout(debounce);
    debounce = setTimeout(() => {
      console.log(dim('change detected...'));
      autoSync(fafPath, claudePath, dir);
      if (isPro()) triSync(fafPath, memoryPath, dir);
    }, 200);
  };

  watch(fafPath, handler);
  if (existsSync(claudePath)) watch(claudePath, handler);
  if (isPro() && existsSync(memoryPath)) watch(memoryPath, handler);
}
